/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as EyeRestRouteImport } from './routes/eye-rest'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as WidgetRouteImport } from './routes/widget'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const EyeRestRoute = EyeRestRouteImport.update({
  id: '/eye-rest',
  path: '/eye-rest',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/eye-rest': typeof EyeRestRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
  '/timer': typeof TimerRoute
  '/widget': typeof WidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/eye-rest': typeof EyeRestRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
  '/timer': typeof TimerRoute
  '/widget': typeof WidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/eye-rest': typeof EyeRestRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/tasks': typeof TasksRoute
  '/timer': typeof TimerRoute
  '/widget': typeof WidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/eye-rest'
    | '/history'
    | '/settings'
    | '/subjects'
    | '/tasks'
    | '/timer'
    | '/widget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/eye-rest'
    | '/history'
    | '/settings'
    | '/subjects'
    | '/tasks'
    | '/timer'
    | '/widget'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/eye-rest'
    | '/history'
    | '/settings'
    | '/subjects'
    | '/tasks'
    | '/timer'
    | '/widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  EyeRestRoute: typeof EyeRestRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  SubjectsRoute: typeof SubjectsRoute
  TasksRoute: typeof TasksRoute
  TimerRoute: typeof TimerRoute
  WidgetRoute: typeof WidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eye-rest': {
      id: '/eye-rest'
      path: '/eye-rest'
      fullPath: '/eye-rest'
      preLoaderRoute: typeof EyeRestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  EyeRestRoute: EyeRestRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  SubjectsRoute: SubjectsRoute,
  TasksRoute: TasksRoute,
  TimerRoute: TimerRoute,
  WidgetRoute: WidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
